
tasks:
  - init: npm 'install' # runs during prebuild

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - pranaygp.vscode-css-peek
    - abusaidm.html-snippets
    - ritwickdey.LiveServer
